#Configuration File

nomeGUI: "Custom GUI" # Nome della gui qui
GUIHeight: 27 # Grandezza GUI

position:  # Posizione degli item nella gui
  mele: 11
  freccia: 13
  canna: 15

glassName:   "x"  # Nome con il quale vedere il vetro qui
glassColor: 7 # ID rispettivo


itemLore:
  mele:
    ON: "§a§lRaccoglimento MELE abilitato"
    OFF: "§c§lRaccoglimento MELE disabilitato"
  freccia:
    ON: "§a§lRaccoglimento FRECCIA abilitato"
    OFF: "§c§lRaccoglimento FRECCIA disabilitato"
  canna:
    ON: "§a§lRaccoglimento CANNA DA PESCA abilitato"
    OFF: "§c§lRaccoglimento CANNA DA PESCA disabilitato"