#Configuration File

nomeGUI: "Custom GUI" # Nome della gui qui
GUIHeight: 27 # Grandezza GUI

position:  # Posizione degli item nella gui
  mele: 11
  freccia: 13
  canna: 15

glassName:   "§c§lYOUR.SERVERIP.COM"  # Nome con il quale vedere il vetro qui
glassColor: 7 # ID rispettivo

itemname:
  mele: "§6§lMELE D'ORO"
  freccia: "§9§lFRECCIA"
  canna: "§8§lCANNA DA PESCA"

status:
  enable: "§aAbilitato"
  disable: "§cDisabilitato"

noPerms: "§cNon hai abbastanza permessi per fare questo!"
reload: "§aConfig ricaricato con successo"