name: PvPAntiDrop
version: '${project.version}'
main: it.samuconfaa.pvpantidrop.PvPAntiDrop
commands:
  drop:
    usage: /drop
  reload:
    description: reload config.yml
    usage: /drop reload
permissions:
  drop.gui:
    description: apre la gui.
    default: true
  drop.reload:
    description: reload config.yml
    default: op

